### ISSUE TITLE
suggestion: split extensions and localizations

### ISSUE THREAD

**Issue by vladmandic** [AUTOMATIC1111/stable-diffusion-webui-extensions#1]
since list of extensions grows and localizations are quite separate feature, why not have two different indexes?

**Comment by dtlnor** [comment]
cuz localization install via extension. Also, by default, the localization is filtered.

**Comment by vladmandic** [comment]
i get that, i'm just trying to break it down a bit so prs to update extensions are smaller/easier.
perhaps pr should be separate individual jsons and main index.json created by github actions?

**Comment by dtlnor** [comment]
I think its not a challenge for the people who is able to write a extension, to edit and update a json file.

**Comment by vladmandic** [comment]
That's fair.
If it were up to me, I'd have one entry per PR and have master index assembled via git action - less chance of a corruption. 
But either works.
