### ISSUE TITLE
sd-webui-model-scanner

### ISSUE THREAD

**Issue by ddomen** [AUTOMATIC1111/stable-diffusion-webui-extensions#102]
Still in testing phase but can create the right awareness around the security theme on model loading.

URL: https://github.com/ddomen/sd-webui-model-scanner

```JSON
{
    "name": "Model Scanner",
    "url": "https://github.com/ddomen/sd-webui-model-scanner",
    "description": "Perform security and sanity check on stable diffusion and ML models (run it before loading them!)",
    "added": <DATE>,
    "tags": ["tab", "models"]
}
```

Long Description:
This extension allow to perform sanity and security check before the `unpickle` process of the model loading, giving a simple UI to interact with two different pickle checkers (also managing their supported extensions):
- https://github.com/zxix/stable-diffusion-pickle-scanner
- https://github.com/mmaitre314/picklescan

**Comment by w-e-w** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/106
