### ISSUE TITLE
sd-webui-danbooru-prompt

### ISSUE THREAD

**Issue by EnsignMK** [AUTOMATIC1111/stable-diffusion-webui-extensions#103]
Tags fetcher of danbooru images link.

URL:https://github.com/EnsignMK/danbooru-prompt

{
    "name": "Danbooru Prompt",
    "url": "https://github.com/EnsignMK/danbooru-prompt",
    "description": "Fetch tags from Danbooru images link",
    "added": "24-06-2023",
    "tags": ["online"]
}

Provide the image link from Danbooru site 
and the extension provides tags of that image.

**Comment by w-e-w** [comment]
added

I noticed that you said in readme.md
> A lot of code I used for this project came from this project: https://github.com/antis0007/sd-webui-gelbooru-prompt

do you know that https://github.com/antis0007/sd-webui-gelbooru-prompt is licensed under [GPL-3.0 license](https://github.com/antis0007/sd-webui-gelbooru-prompt/blob/main/LICENSE)

btw in case you don't know that is a very similar extension https://github.com/Malisius/booru2prompt
