### ISSUE TITLE
Extension 'Detection Detailer' no longer maintained.

### ISSUE THREAD

**Issue by silveroxides** [AUTOMATIC1111/stable-diffusion-webui-extensions#119]
As title says "Detection Detailer", GitHub repo "dustysys/ddetailer" is no longer maintained and no longer compatible with current stable-diffusion-webui due to it lacking support for new torch.
Latest commit: "commit_time": "2022-11-28T09:33:31Z"

There is however a fork that is maintained and it seems to be functional. Last commit was just 2 weeks ago.
I will include link to it here. 
[Bing-su/dddetailer](https://github.com/Bing-su/dddetailer)

**Comment by ClashSAN** [comment]
@silveroxides Thanks for the info. There is !adetailer with the same maintainer. Could you maybe see if that extension fully replaces ddetailer in feature-set? If not we could add this too.

**Comment by silveroxides** [comment]
@ClashSAN sit seems they fulfill similar purpose. Though it might be good to have both still. Different methods for object detection can have different use cases and it would be good to keep the mmdetailer based one for those who need it still.
