### ISSUE TITLE
sd_shutdown_button

### ISSUE THREAD

**Issue by EnsignMK** [AUTOMATIC1111/stable-diffusion-webui-extensions#132]
{
    "name": "Shutdown Button",
    "url": "https://github.com/EnsignMK/sd_shutdown_button",
    "description": "Exit stable diffusion webui easily ",
    "added": <DATE>,
    "tags": ["script", "UI related"]
}

This extension allows you to easily close stable diffusion webui ,by a simple click of the button. It adresses this issue:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2204

**Comment by w-e-w** [comment]
your extension doesn't work
`quicksettings` is deprecated use `quicksettings`
see https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5edb0acfeb424f71954b111910d2e08c410b0c43#diff-15faa364afc7fd40ccc1e6a38893b2dac62c846715710dfbe44f25fb65205440L408-R408
and
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/10209

also there's a graceful way of stopping webui
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/c58cf73c806f08eb8b96bccc2af64403d903695f/modules/api/api.py#L723-L737

> I have a feeling that I spend more time looking up the correct commits to show you then it would take me to add some bottoms to do the same thing myself

**Comment by EnsignMK** [comment]
@w-e-w  thanks for the feedback,time to update my stable webui. I made the changes ,   I don't  know, how pull request work (my bad)  ,is it okay if I sumbit it this way?

**Comment by w-e-w** [comment]
sure I can do it for you
but git is a important tool learn so I suggest you try how to use it
when your extension is ready, leave another comment or try submit via pull request

**Comment by EnsignMK** [comment]
It's ready.
