### ISSUE TITLE
Workflow failure on pull request for extension submission

### ISSUE THREAD

**Issue by pmcculler** [AUTOMATIC1111/stable-diffusion-webui-extensions#146]
I got a failure notice, but I don't understand what's wrong. Would greatly appreciate help.

**Comment by w-e-w** [comment]
you are a bit slow....
I'm already told you the reason and fix it for you
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/145#issuecomment-1646597512
