### ISSUE TITLE
how to update the wiki of main repo 

### ISSUE THREAD

**Issue by jtydhr88** [AUTOMATIC1111/stable-diffusion-webui-extensions#17]
Hi,
As an extension developer for webui, I am wondering how to update this wiki https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions to add my or other's new extension?
This wiki page look likes quite a bit of out of date, but I think most users will get the extensions information from this page.

**Comment by ClashSAN** [comment]
sure, you can ask automatic to add you as collaborator to edit the wiki. he probably only gets notified from the github pull request sections of webui.

I see that page as a newspaper which is a few weeks old. It's interesting but won't be updated very frequently, so for user's it's better to check extension's github.

**Comment by w-e-w** [comment]
@jtydhr88
Wiki edit permission is now open to everyone
we will have to keep an eye on it to prevent vandalism
if that happens then it might be closed again
hopefully that doesn't happen and this will allow the those who are willing to contribute to the the wiki

so now you can make changes to the page you were talking about
