### ISSUE TITLE
Suggestion extensions

### ISSUE THREAD

**Issue by Katehuuh** [AUTOMATIC1111/stable-diffusion-webui-extensions#172]
add
- https://github.com/dvruette/sd-webui-fabric
- https://github.com/Haoming02/sd-webui-prompt-format

**Comment by w-e-w** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/173
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/174
will be added in a week if no objection is raised
