### ISSUE TITLE
Discord Rich Presence extension

### ISSUE THREAD

**Issue by davehornik** [AUTOMATIC1111/stable-diffusion-webui-extensions#21]
Hi, Is it possible to add https://github.com/davehornik/sd-discord-rich_presence/  to the list?

There's already one Discord RPC extension. But its barely working, showing only current model and thats all.
Our version is showing "Idle" status, and will change status when generating to "Generating total batch of XX image/s"

Simple description:
Will show your current sd model selected. Also showing if you are idle, or generating something - in that case, total image/s being generated.

**Comment by w-e-w** [comment]
make a PR, under a new entrey
we do have multiple extensions that serve similar functions

furthermore, some extensions are not actively maintained and stop functioning
if theres a fork we might replace it with the working fork

**Comment by davehornik** [comment]
@w-e-w Done, thanks. 
#22
