### ISSUE TITLE
Dynamic Prompts extention should has "online" tag

### ISSUE THREAD

**Issue by light-and-ray** [AUTOMATIC1111/stable-diffusion-webui-extensions#245]
"Dynamic Prompts" is a great extension. It uses different local models to generate prompts (like GPT-2), but in case when "I'm feeling lucky" checkbox enabled, it sends your prompt to https://lexica.art/. They notice about this behavior in read.me (https://github.com/adieyal/sd-dynamic-prompts#im-feeling-lucky), but they don't in the ui. I think "online" tag is important for this case, despite the main functionality doesn't use external server @adieyal

![Screenshot_20231208_201337](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/assets/33491867/33dbcde0-29f8-40f7-881d-d7e0881e49ba)

**Comment by w-e-w** [comment]
thanks for the report I have confirmed that `I'm feeling lucky` in Dynamic Prompts does indeed called to an external API

**Comment by w-e-w** [comment]
added online tag to Dynamic Prompts
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/246
