### ISSUE TITLE
New extensions metadata not updated

### ISSUE THREAD

**Issue by sontungdo** [AUTOMATIC1111/stable-diffusion-webui-extensions#304]
All the new extensions added in April don't get their metadata automatically updated by Github actions

**Comment by w-e-w** [comment]
thanks

**Comment by w-e-w** [comment]
fixed
the cause was trigger by GitHub account account https://github.com/Animator-Anon was deleted
which used to host this extension https://github.com/Animator-Anon/animator_extension.git
that was a bug in my updating metadata code if the web request returns 404 the code essentially stop will stop
