### ISSUE TITLE
should show github link in the extensions table?

### ISSUE THREAD

**Issue by jtydhr88** [AUTOMATIC1111/stable-diffusion-webui-extensions#35]
(I know this issue may belong to main repo...)
Currently, in the official extension index tab, there are 3 coloums: extension (name), description, action (install). 
It may be better to have another coloum to show the extension github to allow user check more details before they decide to install one extension. Otherwise, they can only go to the github page after they installed.
![image](https://user-images.githubusercontent.com/860985/232650106-4eaa83af-e680-4f7d-8425-2c79c8124841.png)

**Comment by ICYDev** [comment]
You can actually get to the corresponding github pages by clicking on the Extension names on that page, though I do agree it's not obvious that those are hyperlinks.
