### ISSUE TITLE
adding new tag for future (fork-specific) extensions!

### ISSUE THREAD

**Issue by ClashSAN** [AUTOMATIC1111/stable-diffusion-webui-extensions#41]
see future backends for extensions: https://github.com/vladmandic/automatic/pull/593

motivation: reduce user confusion.

alternative: a new list?

**Comment by ICYDev** [comment]
I.. don't get what that link is about and what relation it has with this subject at hand.
But in any case, my proposal would be to have vlad fork this repo as well, and fork specific extensions can go in that forked repo instead.

**Comment by w-e-w** [comment]
I haven't been following development on vlad's fork
but from a quick read I think they are trying to integrate Diffusers as a back end
which means that it will probably need a new set of callbacks for the extensions
meaning that it will not be compatible

so ClashSAN is trying to get feedback on how we should handle this in the future
should we put everything in the same file and just give it a vlad_diffuser tag
or should it be in a separate file / list / fork / repo

**Comment by camenduru** [comment]
that project lost the `keep the core simple` philosophy. I agree with ICYDev.
>fork this repo as well

**Comment by w-e-w** [comment]
me and spartan just had a conversation about compatible extension versions on auto's discord
it's not exactly about this but I think it's kind of related so maybe is a good Idea that you join in

**Comment by ICYDev** [comment]
> on auto's discord
There's a discord?!

**Comment by w-e-w** [comment]
> > on auto's discord
> 
> There's a discord?!

read Wiki contribution page

**Comment by ClashSAN** [comment]
great, thanks!

Maybe the question can also be asked directly and discreetly.
@vladmandic could you tell us how you think we can coordinate via the discord?
The main failure of webui is untidiness in communication.

**Comment by vladmandic** [comment]
@ClashSAN - my discord id is vlado#8083

**Comment by ClashSAN** [comment]
<details>
https://discord.g/fcHmMZVY
</details>

**Comment by ICYDev** [comment]
> > > on auto's discord
> > 
> > 
> > There's a discord?!
> 
> read Wiki contribution page

Invalid or expired 😢

**Comment by w-e-w** [comment]
@ICYDev 
![image](https://user-images.githubusercontent.com/40751091/236594082-0f390237-047f-4036-a87d-af44b3ccb899.png)
are you sure it's broken?
when I click it it still works

**Comment by ICYDev** [comment]
Weird, for me it doesn't work through the browser, but pasting it in the discord add server thing works...
