### ISSUE TITLE
Model Preset Manager

### ISSUE THREAD

**Issue by rifeWithKaiju** [AUTOMATIC1111/stable-diffusion-webui-extensions#56]
https://github.com/rifeWithKaiju/model_preset_manager/

Lets you create, manage and share presets per model including all generation data (e.g. prompt, negative prompt, cfg_scale, resolution, sampler, clip skip, steps, etc).  Also integrates with civitai to download model thumbnails and trigger words. Model presets are shareable.

not sure if the online tag is required:
"online tag is Required for any extension that connections to external server during regular use aside from one time downloading of assets."
It only connects to civitai when you download the model info from the site.  It doesn't have to regularly connect.  So it probably won't be one time use, but any time someone wants to automatically retrieve model info

**Comment by w-e-w** [comment]
so this is a preset manager + civitai integrated downloader

does your extension have issues working with https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper ?

**Comment by rifeWithKaiju** [comment]
it doesn't seem like it should.  The worst that might happen is that one extension overwrites the thumbnail image the other one downloaded (probably with the same image)

**Comment by w-e-w** [comment]
iirc as far as I know Civitai-Helper  doesn't override any data
Civitai-Helper downloads preview images and save it as `model_name.preview.png`

for webui if they exist another image with the same exact name as the model but without the preview  `model_name.png` then this file will be chosen
a user can easily replace the  `model_name.png` image while  `.preview` can remain untouched

well your extension override user generated preview images?

**Comment by rifeWithKaiju** [comment]
I just updated it so it won't overwrite if there is already an image named model_name.png

**Comment by w-e-w** [comment]
I say online, you even use webdriver

yes the preset manager part can work offline
but I think it's safe to say that you designed it with online civitai in mind

go make a PR, tag it appropriately and give it a concise description

**Comment by rifeWithKaiju** [comment]
Thank you.  Done
