### ISSUE TITLE
[request] Sort by Github stars

### ISSUE THREAD

**Issue by GoulartNogueira** [AUTOMATIC1111/stable-diffusion-webui-extensions#97]
## Problem:
There are a lot of similar extensions, and I can't find the best one.
So I manually open the github page for each extension and check their popularity.

## Solution:
I'd like to sort each repo by their github stars, so we can all find the most popular extensions with ease.

It would also help newbies to discover the best extensions.

### Tasks:
1. Make a script to check the stars and update the `index.json` file
2. Update the webui extensions UI to allow `sort by stars`.
3. Periodically run the script manually
4. Automate the script (with some github action).

Can someone help me with that?

**Comment by w-e-w** [comment]
this was considered but no one has gotten around to implement it yet
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9381
